In [1]:
import torch
import numpy as np

In [2]:
a = np.array(1)
print(a, type(a))

1 <class 'numpy.ndarray'>


In [3]:
b = torch.tensor(1)
print(b, type(b))

tensor(1) <class 'torch.Tensor'>


In [4]:
b = np.array(2)

In [5]:
print(a+b, a-b, a*b, a/b)

3 -1 2 0.5


In [6]:
a = torch.tensor(1)
b = torch.tensor(2)
print(a+b, a-b, a*b, a/b)

tensor(3) tensor(-1) tensor(2) tensor(0.5000)


In [7]:
zero = np.zeros((3, 3))
print(zero, zero.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


In [8]:
zero = torch.zeros((3, 3))
print(zero, zero.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.Size([3, 3])


In [13]:
np.random.seed(5)
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
print(a)
print(b)

[[ 0.44122749 -0.33087015  2.43077119]
 [-0.25209213  0.10960984  1.58248112]
 [-0.9092324  -0.59163666  0.18760323]]
[[-0.32986996 -1.19276461 -0.20487651]
 [-0.35882895  0.6034716  -1.66478853]
 [-0.70017904  1.15139101  1.85733101]]


In [14]:
print(np.add(a, b), np.subtract(a, b), a@b, np.divide(a, b), np.transpose(a))

[[ 0.11135753 -1.52363476  2.22589468]
 [-0.61092108  0.71308144 -0.08230741]
 [-1.60941144  0.55975435  2.04493423]] [[ 0.77109744  0.86189446  2.6356477 ]
 [ 0.10673682 -0.49386176  3.24726965]
 [-0.20905337 -1.74302767 -1.66972778]] [[-1.72879693  2.07281682  4.97517838]
 [-1.06419367  2.18888753  2.8083618 ]
 [ 0.38086897  0.94346898  1.51967157]] [[ -1.33758009   0.27739769 -11.86456749]
 [  0.70254123   0.18163214  -0.95055984]
 [  1.2985713   -0.51384513   0.10100689]] [[ 0.44122749 -0.25209213 -0.9092324 ]
 [-0.33087015  0.10960984 -0.59163666]
 [ 2.43077119  1.58248112  0.18760323]]


In [15]:
torch.manual_seed(5)
a = torch.randn(3, 3)
b = torch.randn(3, 3)
print(a)
print(b)

tensor([[-0.4868, -0.6038, -0.5581],
        [ 0.6675, -0.1974,  1.9428],
        [-1.4017, -0.7626,  0.6312]])
tensor([[-0.8991, -0.5578,  0.6907],
        [ 0.2225, -0.6662,  0.6846],
        [ 0.5740, -0.5829,  0.7679]])


In [16]:
print(torch.add(a, b), torch.subtract(a, b), torch.matmul(a, b), torch.div(a, b), torch.t(a))

tensor([[-1.3859, -1.1616,  0.1326],
        [ 0.8900, -0.8636,  2.6274],
        [-0.8277, -1.3454,  1.3992]]) tensor([[ 0.4124, -0.0460, -1.2488],
        [ 0.4451,  0.4688,  1.2581],
        [-1.9757, -0.1797, -0.1367]]) tensor([[-0.0170,  0.9991, -1.1782],
        [ 0.4710, -1.3732,  1.8179],
        [ 1.4530,  0.9220, -1.0055]]) tensor([[ 0.5414,  1.0825, -0.8080],
        [ 3.0007,  0.2963,  2.8377],
        [-2.4420,  1.3083,  0.8220]]) tensor([[-0.4868,  0.6675, -1.4017],
        [-0.6038, -0.1974, -0.7626],
        [-0.5581,  1.9428,  0.6312]])


In [24]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

In [22]:
print(a, b, a.shape, b.shape)

tensor([[1, 2],
        [3, 4]]) tensor([[5, 6],
        [7, 8]]) torch.Size([2, 2]) torch.Size([2, 2])


In [23]:
a = torch.cat((a, b), dim = 1)
print(a, a.shape)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


In [25]:
a = torch.cat((a, b), dim = 0)
print(a, a.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) torch.Size([4, 2])


In [26]:
a = a.reshape(1, 8)
print(a, a.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8]]) torch.Size([1, 8])


In [27]:
a = np.array([[1, 2], [3, 4]])
print(a)
a = torch.from_numpy(a)
print(a)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [34]:
a = torch.ones((2, 2), requires_grad=False)
aa = torch.ones((2, 2), requires_grad=True)

In [35]:
a

tensor([[1., 1.],
        [1., 1.]])

In [36]:
b = a + aa
print(b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [37]:
c = b.mean()
print(c)

tensor(2., grad_fn=<MeanBackward0>)


In [38]:
c.backward()

In [39]:
print(aa.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
